[tool.ruff]
all = true
select = ["E", "F", "I", "B", "C", "Q", "UP"]
ignore = ["E501"]
line-length = 100

[tool.ruff.per-file-ignores]
"*.py" = ["E501"]

[tool.ruff.isort]
force-sort-within-sections = true
known-first-party = ["DMuffler"]

[tool.ruff.flake8]
ignore = ["E501"]

[tool.ruff.format]
line-length = 100
